function sigDEN = sigDEN(SIG)
% FUNC_DENOISE_DW1D Saved Denoising Process.
%   SIG: vector of data
%   -------------------
%   sigDEN: vector of denoised data

%  Auto-generated by Wavelet Toolbox on 16-Sep-2014 10:30:16

% Analysis parameters.
%---------------------
wname = 'haar';
level = 3;

% Denoising parameters.
%----------------------
% meth = 'sqtwolog';
% scal_or_alfa = one;
sorh = 's';    % Specified soft or hard thresholding
thrSettings =  [...
    0.027183546405460 ; ...
    0.018099615000000 ; ...
    0.049130960025166   ...
    ];

% Denoise using CMDDENOISE.
%--------------------------
sigDEN = cmddenoise(SIG,wname,level,sorh,NaN,thrSettings);
sigDEN=sigDEN';
