function sigDEN5 = sigDEN5(SIG)
% FUNC_DENOISE_DW1D Saved Denoising Process.
%   SIG: vector of data
%   -------------------
%   sigDEN: vector of denoised data

%  Auto-generated by Wavelet Toolbox on 18-Nov-2014 14:14:16

% Analysis parameters.
%---------------------
wname = 'haar';
level = 5;

% Denoising parameters.
%----------------------
% meth = 'sqtwolog';
% scal_or_alfa = one;
sorh = 's';    % Specified soft or hard thresholding
thrSettings =  [...
    0.115753380080237 ; ...
    0.253000000000000 ; ...
    0.311515892451732 ; ...
    0.764999999999997 ; ...
    0.618753788877289   ...
    ];

% Denoise using CMDDENOISE.
%--------------------------
sigDEN5 = cmddenoise(SIG,wname,level,sorh,NaN,thrSettings);
