function mesh_figure(xdata1, ydata1, zdata1)
%CREATEFIGURE(XDATA1, YDATA1, ZDATA1)
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata

%  Auto-generated by MATLAB on 04-Jun-2015 19:24:15

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
view(axes1,[-31.5 56]);
grid(axes1,'on');
hold(axes1,'on');

% Create zlabel
zlabel('landscape / kBT');

% Create ylabel
ylabel('force / pN');

% Create xlabel
xlabel('extension / ¦Ìm');

% Create mesh
mesh(xdata1,ydata1,zdata1,'Parent',axes1,'MeshStyle','row');

